import streamlit as st
import os
import json
from datetime import datetime
from groq import Groq
from fpdf import FPDF
import pdfplumber
import pytesseract
from pdf2image import convert_from_bytes
def get_groq_client():
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        st.error("Groq API key not found. Add GROQ_API_KEY to secrets.")
        st.stop()
    return Groq(api_key=api_key)

def generate_quiz(notes, difficulty, num_questions=5):
    client = get_groq_client()
    prompt = "You are a quiz generator. Based on the notes below, generate exactly " + str(num_questions) + " multiple-choice questions.\n\nDifficulty level: " + difficulty + "\n\nNotes:\n" + notes + "\n\nReturn ONLY a valid JSON array with this exact structure (no extra text, no markdown):\n[\n  {\n    \"question\": \"Question text here?\",\n    \"options\": [\"Option A\", \"Option B\", \"Option C\", \"Option D\"],\n    \"answer\": \"Option A\"\n  }\n]\n\nRules:\n- Each question must have exactly 4 options.\n- The answer field must exactly match one of the 4 options.\n- Questions should be based strictly on the provided notes.\n- For Easy: straightforward factual questions.\n- For Medium: questions requiring some understanding.\n- For Hard: questions requiring deep analysis or inference.\n- Generate exactly " + str(num_questions) + " questions, no more, no less."
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.7,
    )
    raw = response.choices[0].message.content.strip()
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
        raw = raw.strip()
    questions = json.loads(raw)
    if not isinstance(questions, list) or len(questions) == 0:
        raise ValueError("Invalid response format from AI.")
    return questions

def build_text(questions, difficulty, include_answers=True):
    lines = []
    lines.append("GyanSetu - AI Quiz")
    lines.append("Difficulty: " + difficulty)
    lines.append("=" * 50)
    lines.append("")
    for i, q in enumerate(questions):
        lines.append("Q" + str(i+1) + ". " + q["question"])
        for j, opt in enumerate(q["options"]):
            label = chr(65 + j)
            lines.append("   " + label + ". " + opt)
        if include_answers:
            lines.append("   Answer: " + q["answer"])
        lines.append("")
    lines.append("=" * 50)
    lines.append("Generated by GyanSetu")
    return "\n".join(lines)

def build_pdf(questions, difficulty, include_answers=True):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, "GyanSetu - AI Quiz", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, "Difficulty: " + difficulty, new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(4)
    pdf.set_draw_color(180, 180, 180)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)
    for i, q in enumerate(questions):
        pdf.set_font("Helvetica", "B", 11)
        pdf.multi_cell(0, 7, "Q" + str(i+1) + ". " + q["question"], new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)
        pdf.set_font("Helvetica", "", 10)
        for j, opt in enumerate(q["options"]):
            label = chr(65 + j)
            pdf.cell(8)
            pdf.multi_cell(0, 6, label + ".  " + opt, new_x="LMARGIN", new_y="NEXT")
        if include_answers:
            pdf.set_font("Helvetica", "I", 10)
            pdf.set_text_color(0, 128, 0)
            pdf.cell(8)
            pdf.multi_cell(0, 6, "Answer: " + q["answer"], new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(0, 0, 0)
        pdf.ln(4)
    pdf.set_draw_color(180, 180, 180)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 6, "Generated by GyanSetu", align="C")
    return bytes(pdf.output())

def extract_text_from_pdf(uploaded_file):
    with pdfplumber.open(uploaded_file) as pdf:
        pages = [page.extract_text() or "" for page in pdf.pages]

    text = "\n".join(pages).strip()

    # If very little text found, use OCR
    if len(text) < 500:
        uploaded_file.seek(0)

        images = convert_from_bytes(uploaded_file.read())

        for img in images:
            text += pytesseract.image_to_string(img)

    if not text:
        raise ValueError("Could not extract text from PDF.")

    return text

def load_quiz_from_history(entry):
    st.session_state["questions"] = entry["questions"]
    st.session_state["difficulty"] = entry["difficulty"]
    st.session_state["user_answers"] = [None] * len(entry["questions"])
    st.session_state["submitted"] = False
    st.session_state["score"] = 0

st.set_page_config(page_title="GyanSetu", page_icon="🎓", layout="centered")

if "quiz_history" not in st.session_state:
    st.session_state["quiz_history"] = []

with st.sidebar:
    st.header("Quiz History")
    history = st.session_state["quiz_history"]
    if not history:
        st.caption("No quizzes yet. Generate your first quiz to see it here!")
    else:
        st.caption(str(len(history)) + " quiz this session")
        for idx, entry in enumerate(reversed(history)):
            pos = len(history) - 1 - idx
            label = "#" + str(pos+1) + " " + entry["difficulty"] + " " + entry["timestamp"]
            score_text = "Score: " + str(entry["score"]) + "/" + str(entry["total"]) if entry.get("score") is not None else "Not attempted"
            with st.expander(label):
                st.caption(score_text)
                st.caption("First question: " + entry["questions"][0]["question"][:60])
                if st.button("Re-take this quiz", key="retake_" + str(pos)):
                    load_quiz_from_history(entry)
                    st.rerun()
        st.divider()
        if st.button("Clear History", use_container_width=True):
            st.session_state["quiz_history"] = []
            for key in ["questions", "user_answers", "submitted", "score", "difficulty"]:
                st.session_state.pop(key, None)
            st.rerun()

st.title("GyanSetu")
st.write("Upload a PDF or paste your notes, pick a difficulty, and let AI generate a quiz for you!")
st.divider()

tab_paste, tab_pdf = st.tabs(["Paste Notes", "Upload PDF"])
notes = ""

with tab_paste:
    notes_input = st.text_area("Paste your notes here", height=220, key="notes_text")

with tab_pdf:
    uploaded_file = st.file_uploader("Upload a PDF file", type=["pdf"])
    if uploaded_file is not None:
        try:
            extracted = extract_text_from_pdf(uploaded_file)
            st.success("PDF loaded - " + str(len(extracted.split())) + " words extracted.")
            st.text_area("Extracted text preview", extracted[:800], height=160, disabled=True)
        except Exception as e:
            st.error("Could not read PDF: " + str(e))
            extracted = ""
    else:
        extracted = ""

notes = extracted if extracted else notes_input

col_left, col_right = st.columns(2)
with col_left:
    difficulty = st.selectbox("Difficulty level", options=["Easy", "Medium", "Hard"])
with col_right:
    num_questions = st.number_input("Number of questions", min_value=1, max_value=30, value=5, step=1)

generate_btn = st.button("Generate Quiz", type="primary", use_container_width=True)

if generate_btn:
    if not notes.strip():
        st.warning("Please paste some notes or upload a PDF before generating a quiz.")
    else:
        with st.spinner("Generating questions..."):
            try:
                questions = generate_quiz(notes.strip(), difficulty, int(num_questions))
                st.session_state["questions"] = questions
                st.session_state["difficulty"] = difficulty
                st.session_state["user_answers"] = [None] * len(questions)
                st.session_state["submitted"] = False
                st.session_state["score"] = 0
                st.session_state["quiz_history"].append({
                    "questions": questions,
                    "difficulty": difficulty,
                    "timestamp": datetime.now().strftime("%H:%M"),
                    "score": None,
                    "total": len(questions),
                })
                st.session_state["current_history_index"] = len(st.session_state["quiz_history"]) - 1
            except json.JSONDecodeError:
                st.error("The AI returned an unexpected format. Please try again.")
                st.stop()
            except Exception as e:
                st.error("An error occurred: " + str(e))
                st.stop()

if "questions" in st.session_state and st.session_state["questions"]:
    questions = st.session_state["questions"]
    saved_difficulty = st.session_state.get("difficulty", difficulty)
    st.divider()
    st.subheader("Your Quiz - " + saved_difficulty + " difficulty")
    user_answers = st.session_state.get("user_answers", [None] * len(questions))
    submitted = st.session_state.get("submitted", False)

    for i, q in enumerate(questions):
        st.markdown("**Question " + str(i+1) + ": " + q["question"] + "**")
        options = q.get("options", [])
        correct = q.get("answer", "")
        if submitted:
            selected = user_answers[i]
            for opt in options:
                if opt == correct:
                    st.markdown("correct: " + opt)
                elif opt == selected and selected != correct:
                    st.markdown("wrong: " + opt)
                else:
                    st.markdown(opt)
            if selected is None:
                st.caption("You did not answer this question.")
            elif selected == correct:
                st.caption("Correct!")
            else:
                st.caption("Your answer: " + str(selected) + " - Correct answer: " + correct)
        else:
            selected = st.radio(label="q"+str(i), options=options, index=None, key="q_"+str(i), label_visibility="collapsed")
            user_answers[i] = selected
        st.write("")

    st.session_state["user_answers"] = user_answers

    if not submitted:
        st.divider()
        if st.button("Submit Answers", type="primary", use_container_width=True):
            score = sum(1 for i, q in enumerate(questions) if user_answers[i] == q.get("answer"))
            st.session_state["submitted"] = True
            st.session_state["score"] = score
            hist_idx = st.session_state.get("current_history_index")
            if hist_idx is not None:
                st.session_state["quiz_history"][hist_idx]["score"] = score
            st.rerun()
    else:
        st.divider()
        score = st.session_state.get("score", 0)
        total = len(questions)
        pct = int((score / total) * 100)
        if pct == 100:
            st.success("Perfect score! You got " + str(score) + "/" + str(total))
        elif pct >= 60:
            st.info("Good job! You got " + str(score) + "/" + str(total))
        else:
            st.warning("Keep studying! You got " + str(score) + "/" + str(total))
        st.divider()
        st.subheader("Save Your Quiz")
        include_answers = st.checkbox("Include answer key", value=True)
        col1, col2 = st.columns(2)
        with col1:
            try:
                pdf_bytes = build_pdf(questions, saved_difficulty, include_answers)
                st.download_button(label="Download as PDF", data=pdf_bytes, file_name="gyansetu_quiz.pdf", mime="application/pdf", use_container_width=True)
            except Exception as e:
                st.error("PDF generation failed: " + str(e))
        with col2:
            txt = build_text(questions, saved_difficulty, include_answers)
            st.download_button(label="Download as Text", data=txt.encode("utf-8"), file_name="gyansetu_quiz.txt", mime="text/plain", use_container_width=True)
        st.divider()
        if st.button("Try Again", use_container_width=True):
            for key in ["questions", "user_answers", "submitted", "score", "difficulty"]:
                st.session_state.pop(key, None)
            st.rerun()
