import streamlit as st
import os
import json
from datetime import datetime
from groq import Groq
from fpdf import FPDF
import pdfplumber

# ============================================================
# CONFIGURATION
# ============================================================

def get_groq_client():
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        st.error(
            "Groq API key not found. Please add your key as a secret named "
            "**GROQ_API_KEY** in the Replit Secrets tab (lock icon in the left sidebar). "
            "Get a free key at https://console.groq.com"
        )
        st.stop()
    return Groq(api_key=api_key)


def generate_quiz(notes: str, difficulty: str, num_questions: int = 5) -> list[dict]:
    client = get_groq_client()

    prompt = f"""You are a quiz generator. Based on the notes below, generate exactly {num_questions} multiple-choice questions.

Difficulty level: {difficulty}

Notes:
{notes}

Return ONLY a valid JSON array with this exact structure (no extra text, no markdown):
[
  {{
    "question": "Question text here?",
    "options": ["Option A", "Option B", "Option C", "Option D"],
    "answer": "Option A"
  }}
]

Rules:
- Each question must have exactly 4 options.
- The "answer" field must exactly match one of the 4 options.
- Questions should be based strictly on the provided notes.
- For Easy: straightforward factual questions.
- For Medium: questions requiring some understanding.
- For Hard: questions requiring deep analysis or inference.
- Generate exactly {num_questions} questions, no more, no less.
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.7,
    )

    raw = response.choices[0].message.content.strip()

    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
        raw = raw.strip()

    questions = json.loads(raw)

    if not isinstance(questions, list) or len(questions) == 0:
        raise ValueError("Invalid response format from AI.")

    return questions


def build_text(questions: list[dict], difficulty: str, include_answers: bool = True) -> str:
    lines = []
    lines.append("GyanSetu — AI Quiz")
    lines.append(f"Difficulty: {difficulty}")
    lines.append("=" * 50)
    lines.append("")

    for i, q in enumerate(questions):
        lines.append(f"Q{i + 1}. {q['question']}")
        for j, opt in enumerate(q["options"]):
            label = chr(65 + j)
            lines.append(f"   {label}. {opt}")
        if include_answers:
            lines.append(f"   Answer: {q['answer']}")
        lines.append("")

    lines.append("=" * 50)
    lines.append("Generated by GyanSetu")
    return "\n".join(lines)


def build_pdf(questions: list[dict], difficulty: str, include_answers: bool = True) -> bytes:
    pdf = FPDF()
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, "GyanSetu - AI Quiz", new_x="LMARGIN", new_y="NEXT", align="C")

    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, f"Difficulty: {difficulty}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(4)

    pdf.set_draw_color(180, 180, 180)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    for i, q in enumerate(questions):
        pdf.set_font("Helvetica", "B", 11)
        pdf.multi_cell(0, 7, f"Q{i + 1}. {q['question']}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)

        pdf.set_font("Helvetica", "", 10)
        for j, opt in enumerate(q["options"]):
            label = chr(65 + j)
            pdf.cell(8)
            pdf.multi_cell(0, 6, f"{label}.  {opt}", new_x="LMARGIN", n
